//
//  DatabaseConstants.h
//  KGK Monitoring
//
//  Created by Admin on 13/11/15.
//  Copyright (c) 2015 KGK. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface DatabaseConstants : NSObject

FOUNDATION_EXPORT NSString *const DATABASE_NAME;
FOUNDATION_EXPORT NSString *const TABLE_SIGNAL;
FOUNDATION_EXPORT NSString *const COLUMN_ID;
FOUNDATION_EXPORT NSString *const COLUMN_DEVICE_ID;
FOUNDATION_EXPORT NSString *const COLUMN_MODE;
FOUNDATION_EXPORT NSString *const COLUMN_LATITUDE;
FOUNDATION_EXPORT NSString *const COLUMN_LONGITUDE;
FOUNDATION_EXPORT NSString *const COLUMN_DATE;
FOUNDATION_EXPORT NSString *const COLUMN_VOLTAGE;
FOUNDATION_EXPORT NSString *const COLUMN_BALANCE;
FOUNDATION_EXPORT NSString *const COLUMN_SATELLITES;
FOUNDATION_EXPORT NSString *const COLUMN_SPEED;
FOUNDATION_EXPORT NSString *const COLUMN_CHARGE;
FOUNDATION_EXPORT NSString *const COLUMN_DIRECTION;
FOUNDATION_EXPORT NSString *const COLUMN_TEMPERATURE;

@end
