//
//  KGKHttpConstants.h
//  KGK Monitoring
//
//  Created by Admin on 11/11/15.
//  Copyright (c) 2015 KGK. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface KGKHttpConstants : NSObject

FOUNDATION_EXPORT NSString *const AUTHENTICATION_URL;
FOUNDATION_EXPORT NSString *const LOGIN_SUCCESS;
FOUNDATION_EXPORT NSString *const LOGIN_FAILED;
FOUNDATION_EXPORT NSString *const LOGIN_ERROR;
FOUNDATION_EXPORT NSString *const LOGIN_NO_DEVICES;

FOUNDATION_EXPORT NSString *const DEVICE_LIST_URL;

FOUNDATION_EXPORT NSString *const GET_LAST_SIGNALS_URL;
FOUNDATION_EXPORT NSString *const INSERT_SIGNAL_TO_PERSISTANCE_STORAGE;

FOUNDATION_EXPORT NSString *const QUERY_BEACON_URL;

FOUNDATION_EXPORT NSString *const TOGGLE_SEARCH_MODE_REQUEST_URL;

FOUNDATION_EXPORT NSString *const SETTINGS_REQUEST_URL;

FOUNDATION_EXPORT NSString *const STARTED;
FOUNDATION_EXPORT NSString *const SUCCESS;
FOUNDATION_EXPORT NSString *const ERROR;

@end
